---
# role: jomrr.hostname
# file: tasks/main.yml

- name: "Install packages for ansible-role-hostname"
  ansible.builtin.package:
    name: "{{ hostname_packages }}"
    state: present

- name: "Set hostname"
  ansible.builtin.hostname:
    name: "{{ hostname }}"
  register: hostname_change
  notify:
    - restart hostname
    - restart systemd-logind
    - gather facts
  when: ansible_virtualization_role == 'host'
    or (ansible_virtualization_role == 'guest'
    and ansible_virtualization_type not in ['docker', 'lxc', 'podman'])
