---
# role: hostname
# file: tasks/main.yml

- name: "HOSTNAME | Load platform packages"
  ansible.builtin.include_vars: "{{ ansible_facts.os_family }}.yml"

- name: "HOSTNAME | Install hostname utilities"
  become: true
  become_user: root
  ansible.builtin.package:
    name: "{{ __hostname_packages }}"
    state: present

- name: "HOSTNAME | Set the system hostname"
  become: true
  become_user: root
  ansible.builtin.hostname:
    name: "{{ hostname_name }}"
  when: "'container' not in ansible_facts.virtualization_tech_guest"
