---
# role: jomrr.hostname
# file: handlers/main.yml

- name: "Restart hostname"
  ansible.builtin.service:
    name: hostname
    state: restarted
  when: ansible_service_mgr != 'systemd'

- name: "Restart systemd-logind"
  ansible.builtin.service:
    name: systemd-logind
    state: restarted
  when: ansible_service_mgr == 'systemd'

- name: "Gather facts"
  ansible.builtin.gather_facts:
