---
# role: jomrr.hostname
# file: molecule/resources/playbooks/converge.yml

- name: Converge
  hosts: all
  become: true
  gather_facts: true
  vars:
    hostname_role_enabled: true
  roles:    # to enable required roles put them in requirements.yml and add here
    - role: "{{ lookup('ansible.builtin.env', 'MOLECULE_PROJECT_DIRECTORY') }}"
