---
# role: hostname
# file: molecule/resources/playbooks/prepare.yml

- name: "HOSTNAME | Wait for test containers"
  hosts: all
  gather_facts: false
  tasks:
    - name: "HOSTNAME | Wait for Ansible connectivity"
      ansible.builtin.wait_for_connection:
        timeout: 60

- name: "HOSTNAME | Prepare package metadata"
  hosts: all
  gather_facts: true
  tasks:
    - name: "HOSTNAME | Refresh Debian package metadata"
      become: true
      become_user: root
      ansible.builtin.apt:
        update_cache: true
      when: ansible_facts.pkg_mgr == 'apt'
